spring:
  cloud:
    gateway:
      routes:
        - id: auth
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**, /users/**
          filters:
            - AuthFilter
        - id: product
          uri: lb://PRODUCT
          predicates:
            - Path=/products/**
          filters:
            - AuthFilter
        - id: cart-orders
          uri: lb://CART-ORDERS
          predicates:
            - Path=/order/**, /cart/**
          filters:
            - AuthFilter
        - id: review
          uri: lb://REVIEW
          predicates:
            - Path=/review/**
          filters:
            - AuthFilter

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

server:
  port: 8083

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.springframework.cloud.gateway: DEBUG
